language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database sonosnprone;' -U postgres
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10