language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c 'create database sonosnprone;' -U travis
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  - JDBC_DATABASE_URL="jdbc:postgresql://localhost:5433/sonosnprone?user=travis&password="